CREATE SCHEMA IF NOT EXISTS core_users;

CREATE TABLE IF NOT EXISTS core_users.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT chk_user_name_length CHECK (LENGTH(name) >= 2 AND LENGTH(name) <= 255),
    CONSTRAINT chk_user_email_length CHECK (LENGTH(email) >= 5 AND LENGTH(email) <= 255)
);