CREATE SCHEMA IF NOT EXISTS core_requests;

DROP TABLE IF EXISTS core_requests.requests CASCADE;

CREATE TABLE IF NOT EXISTS core_requests.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX IF NOT EXISTS idx_requests_event_id ON core_requests.requests(event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester_id ON core_requests.requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON core_requests.requests(status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_requests_event_requester
    ON core_requests.requests(event_id, requester_id);