CREATE SCHEMA IF NOT EXISTS core_events;

CREATE TABLE IF NOT EXISTS core_events.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS core_events.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    confirmed_requests INTEGER DEFAULT 0,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(7000),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT TRUE,
    state VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES core_events.categories(id) ON DELETE RESTRICT
    --CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES core_users.users(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON core_events.events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_category_id ON core_events.events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON core_events.events(state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON core_events.events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_published_on ON core_events.events(published_on);

CREATE TABLE IF NOT EXISTS core_events.compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS core_events.compilations_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES core_events.compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES core_events.events(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_compilations_events_event_id ON core_events.compilations_events(event_id);
CREATE INDEX IF NOT EXISTS idx_compilations_events_compilation_id ON core_events.compilations_events(compilation_id);